# Example workflow for PR style review
name: Style Guide Review

on:
  pull_request:
    paths:
      - 'lectures/**/*.md'

jobs:
  style-check:
    runs-on: ubuntu-latest
    name: Style Guide Review
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run style guide checker
        uses: QuantEcon/meta/.github/actions/style-guide-checker@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          docs: 'lectures'
          mode: 'pr'
          confidence-threshold: 'high'