name: 'QuantEcon Weekly Report'
description: 'Generate a weekly report of issues and PRs across QuantEcon repositories'
author: 'QuantEcon'

inputs:
  github-token:
    description: 'GitHub token with access to the QuantEcon organization'
    required: true
  organization:
    description: 'GitHub organization name'
    required: false
    default: 'QuantEcon'
  output-format:
    description: 'Output format for the report (markdown, json)'
    required: false
    default: 'markdown'
  exclude-repos:
    description: 'Comma-separated list of repository names to exclude from the report'
    required: false
    default: ''
  api-delay:
    description: 'Delay in seconds between API calls to avoid rate limits (0 = no delay)'
    required: false
    default: '0'

outputs:
  report-content:
    description: 'The generated weekly report content'
  report-summary:
    description: 'A brief summary of the report metrics'

runs:
  using: 'composite'
  steps:
    - name: Generate weekly report
      shell: bash
      run: ${{ github.action_path }}/generate-report.sh
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_ORGANIZATION: ${{ inputs.organization }}
        INPUT_OUTPUT_FORMAT: ${{ inputs.output-format }}
        INPUT_EXCLUDE_REPOS: ${{ inputs.exclude-repos }}
        INPUT_API_DELAY: ${{ inputs.api-delay }}