name: QuantEcon Style Guide Check

"on":
  issue_comment:
    types: [created]

jobs:
  style-check:
    # Only run on comments that contain the trigger phrase
    if: contains(github.event.comment.body, '@qe-style-check')
    runs-on: ubuntu-latest
    name: Process style guide check request
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Need full history for PR processing
          fetch-depth: 0
          # Use the head ref for PR comments, default branch for issue comments
          ref: ${{ github.event.issue.pull_request && github.event.pull_request.head.ref || github.sha }}

      - name: Check if user has permissions
        id: check-permissions
        uses: actions/github-script@v7
        with:
          script: |
            const { data: permissions } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.payload.comment.user.login
            });
            
            const hasPermissions = ['write', 'admin', 'maintain'].includes(permissions.permission);
            
            if (!hasPermissions) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: '⚠️ Sorry, only collaborators with write access can trigger style guide checks.'
              });
              core.setFailed('User does not have sufficient permissions');
              return;
            }
            
            core.setOutput('has-permissions', 'true');

      - name: React to comment
        if: steps.check-permissions.outputs.has-permissions == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            });

      - name: Run style guide check
        if: steps.check-permissions.outputs.has-permissions == 'true'
        id: style-check
        uses: .//.github/actions/qe-style-guide
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          style-guide: '.github/copilot-qe-style-guide.md'
          docs: 'lectures/'
          extensions: 'md'
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          model: 'gpt-4'
          max-suggestions: '20'
          confidence-threshold: '0.8'

      - name: React with success/failure
        if: always() && steps.check-permissions.outputs.has-permissions == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const success = '${{ steps.style-check.outcome }}' === 'success';
            const reaction = success ? 'hooray' : 'confused';
            
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: reaction
            });
            
            if (!success) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: '❌ Style guide check failed. Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
              });
            }

      - name: Post summary comment
        if: steps.check-permissions.outputs.has-permissions == 'true' && steps.style-check.outputs.files-processed > 0
        uses: actions/github-script@v7
        with:
          script: |
            const filesProcessed = '${{ steps.style-check.outputs.files-processed }}';
            const suggestionsCount = '${{ steps.style-check.outputs.suggestions-count }}';
            const changesMade = '${{ steps.style-check.outputs.changes-made }}';
            
            let summaryMessage = `## 📊 Style Guide Check Summary\n\n`;
            summaryMessage += `- **Files processed:** ${filesProcessed}\n`;
            summaryMessage += `- **Suggestions found:** ${suggestionsCount}\n`;
            summaryMessage += `- **Changes made:** ${changesMade === 'true' ? 'Yes' : 'No'}\n\n`;
            
            if (changesMade === 'true') {
              summaryMessage += `✅ Style guide processing completed successfully!\n\n`;
            } else if (suggestionsCount > 0) {
              summaryMessage += `ℹ️ Found suggestions but no automatic changes were applied.\n\n`;
            } else {
              summaryMessage += `✨ No style issues found - great work!\n\n`;
            }
            
            summaryMessage += `*Check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for detailed information.*`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: summaryMessage
            });