name: Test Warning Check Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-clean-files:
    runs-on: ubuntu-latest
    name: Test with clean HTML files
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test action with clean files
        id: clean-test
        uses: .//.github/actions/check-warnings
        with:
          html-path: './test/check-warnings/clean.html'
          fail-on-warning: 'false'
      
      - name: Verify clean results
        run: |
          echo "Warnings found: ${{ steps.clean-test.outputs.warnings-found }}"
          echo "Warning count: ${{ steps.clean-test.outputs.warning-count }}"
          if [ "${{ steps.clean-test.outputs.warnings-found }}" != "false" ]; then
            echo "❌ Expected no warnings but found some"
            exit 1
          fi
          echo "✅ Clean test passed"

  test-files-with-warnings:
    runs-on: ubuntu-latest
    name: Test with HTML files containing warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test action with files containing warnings
        id: warning-test
        uses: .//.github/actions/check-warnings
        with:
          html-path: './test/check-warnings'
          fail-on-warning: 'false'
      
      - name: Verify warning results
        run: |
          echo "Warnings found: ${{ steps.warning-test.outputs.warnings-found }}"
          echo "Warning count: ${{ steps.warning-test.outputs.warning-count }}"
          echo "Warning details: ${{ steps.warning-test.outputs.warning-details }}"
          if [ "${{ steps.warning-test.outputs.warnings-found }}" != "true" ]; then
            echo "❌ Expected warnings but found none"
            exit 1
          fi
          if [ "${{ steps.warning-test.outputs.warning-count }}" -lt "3" ]; then
            echo "❌ Expected at least 3 warnings but found ${{ steps.warning-test.outputs.warning-count }}"
            exit 1
          fi
          echo "✅ Warning test passed"

  test-fail-on-warning:
    runs-on: ubuntu-latest
    name: Test fail-on-warning functionality
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test that action fails when warnings found and fail-on-warning is true
        id: fail-test
        continue-on-error: true
        uses: .//.github/actions/check-warnings
        with:
          html-path: './test/check-warnings/with-warnings.html'
          fail-on-warning: 'true'
      
      - name: Verify action failed
        run: |
          if [ "${{ steps.fail-test.outcome }}" != "failure" ]; then
            echo "❌ Expected action to fail but it succeeded"
            exit 1
          fi
          echo "✅ Fail-on-warning test passed"

  test-new-warning-types:
    runs-on: ubuntu-latest
    name: Test new warning types (UserWarning, RuntimeWarning, etc.)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test action with new warning types
        id: new-warning-test
        uses: .//.github/actions/check-warnings
        with:
          html-path: './test/check-warnings/with-new-warnings.html'
          fail-on-warning: 'false'
      
      - name: Verify new warning types are detected
        run: |
          echo "Warnings found: ${{ steps.new-warning-test.outputs.warnings-found }}"
          echo "Warning count: ${{ steps.new-warning-test.outputs.warning-count }}"
          echo "Warning details: ${{ steps.new-warning-test.outputs.warning-details }}"
          if [ "${{ steps.new-warning-test.outputs.warnings-found }}" != "true" ]; then
            echo "❌ Expected new warning types to be found but found none"
            exit 1
          fi
          if [ "${{ steps.new-warning-test.outputs.warning-count }}" -lt "5" ]; then
            echo "❌ Expected at least 5 new warning types but found ${{ steps.new-warning-test.outputs.warning-count }}"
            exit 1
          fi
          # Check that specific new warning types are detected
          if [[ "${{ steps.new-warning-test.outputs.warning-details }}" != *"UserWarning"* ]]; then
            echo "❌ UserWarning not detected"
            exit 1
          fi
          if [[ "${{ steps.new-warning-test.outputs.warning-details }}" != *"RuntimeWarning"* ]]; then
            echo "❌ RuntimeWarning not detected"
            exit 1
          fi
          if [[ "${{ steps.new-warning-test.outputs.warning-details }}" != *"ResourceWarning"* ]]; then
            echo "❌ ResourceWarning not detected"
            exit 1
          fi
          echo "✅ New warning types test passed"